In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import IncrementalPCA
%matplotlib notebook

In [2]:
X = np.array([[-1, 1],
              [1, 2],
              [0, -1],
              [2, -1],
              [2, 0],
              [3, 1]
             ])

# PCA from sklearn

In [17]:
ipca = IncrementalPCA(n_components=1)

In [18]:
ipca.fit(X)

IncrementalPCA(batch_size=None, copy=True, n_components=1, whiten=False)

In [19]:
x_trans = ipca.transform(X)
x_trans -= x_trans[0]
x_trans

array([[0.        ],
       [1.89717781],
       [1.18351864],
       [3.17466834],
       [3.08069645],
       [3.9822994 ]])

# Calculate PCA:
Assume that $u_1$ is the normal vector: <br />
The sample mean of data is $\bar{x}=\frac{1}{N}\sum_{n=1}^Nx_n$ <br />
The variance of projected data is given by:  <br />
            $\frac{1}{N}\sum_{n=1}^N\{u_1^Tx_n - u_1^T\bar{x}\}^2 = u_1^TSu_1$ <br />
Where S is the data covariance matrix (Scatter matrix) define by: <br />
            $S = \frac{1}{N}\sum_{n=1}^N(x_n - \bar{x})(x_n - \bar{x})^T$

In [6]:
x_bar = np.mean(X, axis =0)
x_bar = np.reshape(x_bar, newshape=[2,1])
print("Sample mean:\n {}:".format(x_bar))

N, M = X.shape
S_ = np.zeros((M,M))

for x in X:
    x = np.reshape(x, newshape=[2,1])
    S_ += np.dot((x-x_bar), (x-x_bar).T)

S = S_/N
print("Sample variance (Scatter matrix):\n {}:".format(S))

Sample mean:
 [[1.16666667]
 [0.33333333]]:
Sample variance (Scatter matrix):
 [[ 1.80555556 -0.05555556]
 [-0.05555556  1.22222222]]:


## Maximizing variance by Larrange multiplier
When maximizing variance $u_1^TSu_1$ w.r.t $u_1$. Clearly, this has to be constrained maximization to prevent $||u_1|| \to \infty$. The appropriate constraint comes from the normalization condition $u_1^Tu_1 = 1$

In [7]:
eig_vals, eig_vecs = np.linalg.eig(S)
print("Eigenvector:\n {}".format(eig_vecs))
print("Eigenvalue:\n {}".format(eig_vals))

Eigenvector:
 [[ 0.99557485  0.09397189]
 [-0.09397189  0.99557485]]
Eigenvalue:
 [1.81079942 1.21697836]


In [8]:
u1 = eig_vecs[0]
x_trans = np.dot(X, u1)
x_trans -= x_trans[0]
x_trans

array([0.        , 2.08512159, 0.80763106, 2.79878076, 2.89275266,
       3.9822994 ])

In [10]:
u2 = eig_vecs[1]
x_trans = np.dot(X, u2)

# give bias
x_trans -= x_trans[0]
x_trans

array([ 0.        ,  0.80763106, -2.08512159, -2.27306538, -1.27749053,
       -0.37588757])